### ISSUE TITLE
WP-SCSS compatibility with 4.0

### ISSUE THREAD

**Issue by Tanmccuin** [saltnpixels/ignition#11]
I'm about to start my first build using Ignition after abandoning my own bones / flexbox based starter and while i know the previous version of ignition worked with wp-scss (useful for compiling changes after launch say.) i'm curious if v4 continues that compatibility and if so - what output settings show be used?  

Thanks and much appreciate the work you've done here - i've been scouring the web for a starter theme with the right combination of technology / workflow / and approachability. So many are great but over engineered to the point of not really being "WordPress" anymore, yours feels WordPressy while making a number of workflow improvements. Kudos!

**Comment by saltnpixels** [comment]
Currently it uses webpack to consume the scss files.
It also uses wildcards and globs to allow for scss files in other folders outside sass...

The way I do it is by using github workflows.

I create a git repo. Then pull and push. 
On push the files get compiled and then ftp up to where I want them.

**Comment by saltnpixels** [comment]
I create a workflow like this:
You'll need to create a password in your github settings.
also change the server ftp info...

``` YAML
# This is a basic workflow to help you get started with Actions

name: Publish Website

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: 10.x
      - run: npm  install
      - run: npm run build --if-present
      - name: Upload build files to FTP-Deploy-Action
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist

  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: Download build files from build
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: 123.45.67.89
          FTP_USERNAME: ftp-username
          FTP_PASSWORD: ${{ secrets.FTP_PASS }}
          REMOTE_DIR: public_html/wp-content/themes/yourtheme
          ARGS: --delete --exclude=.ftpquota --exclude-glob=.git*/** --exclude-glob=.git**
          # --delete arg will delete files on the server if you've deleted them in git
```
